### ISSUE TITLE
TODO: Basic Layout

### ISSUE THREAD

**Issue by khaledallen** [khaledallen/latexnotes#3]
- [ ] Left side text editor
- [ ] Right side renderer
- [ ] Search bar (maybe this comes up with a popup under the cursor?)
